apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alertmanager-config
  namespace: monitoring
spec:
  route:
    receiver: 'email'
    repeatInterval: 30m
    routes:
    - matchers:
      - name: alertname
        value: HostHighCpuLoad
    - matchers:
      - name: alertname
        value: KubernetesPodCrashLooping
      repeatInterval: 10m
  receivers:
    - name: 'email'
      emailConfigs:
      - to: 'iankisali@gmail.com'
        from: 'iankisali@gmail.com'
        smarthost: smtp.gmail.com:587
        authUsername: 'iankisali@gmail.com'
        authIdentity: 'iankisali@gmail.com'
        authPassword:
          name: gmail-auth
          key: password
